name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'master'
      - 'release-*'
  push:
    branches: 
      - 'master'
      - 'beta'
      - 'release-*'
      - 'beta-corona'

jobs:
  build:
    name: Build
    env:
      GIT_REF: ${{ github.ref }}
      GIT_SHA: ${{ github.sha }}
      POM_PATH: ./pom.xml
      VERSION_SCRIPT: ./.github/updatePOMVersion.sh
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.9

    - name: Setup Maven settings
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github-genexuslabs", "url": "https://maven.pkg.github.com/genexuslabs/Private-Maven-for-GX",  "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } },
                        { "id": "github", "url": "https://maven.pkg.github.com/github/JavaClasses",  "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
        servers: '[{ "id": "github-genexuslabs", "username": "genexusbot", "password": "${{ secrets.SECURE_TOKEN }}" },
                   { "id": "github", "username": "genexusbot", "password": "${{ secrets.SECURE_TOKEN }}" },
                   { "id": "gpg.passphrase", "passphrase": "${{ secrets.MAVEN_GPG_BUILDER_PASSPHRASE }}" }]'

    - name: Configure GPG Key
      env:
        GPG_SIGNING_KEY: ${{ secrets.MAVEN_GPG_BUILDER_PRIVATE_KEY }}
      run: |
        echo -n "$GPG_SIGNING_KEY" | gpg --import --batch

    - name: Calculate build variables
      id: buildVariables
      run: |
        if ! [[ "$GIT_REF" =~ 'release-.+$' ]]; then
          CommitNumber=$(git rev-list --count HEAD)
        else
          CommitNumber=$(git rev-list --count origin/master..)
        fi

        LastCommitter=$(git log -1 --pretty=format:%an)
        CommitMessage=$(git log -1 --pretty=%B)

        echo "::set-output name=CommitNumber::$CommitNumber"
        echo "::set-output name=LastCommitter::$LastCommitter"
        echo "::set-output name=CommitMessage::$CommitMessage"

    - name: Update POM version
      id: POMVersion
      run: |
        script="$VERSION_SCRIPT"
        if [ -f "$script" ]; then
          echo "Executing version script at: $script"
          "$script"
        else
          echo 'No version script specified. Will generate packages with the version on the POM file'
        fi

        finalPOMVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file $POM_PATH)
        echo "Project version: $finalPOMVersion"
        echo "::set-output name=finalPOMVersion::$finalPOMVersion"

    - name: Validate build
      run: mvn -B validate --file $POM_PATH -P ci-cd

    - name: Build
      run: mvn -B compile --file $POM_PATH -P ci-cd

    - name: Test
      run: mvn -B test --file $POM_PATH -P ci-cd

    - name: Package
      run: mvn -B package -DdeployAtEnd=true --file $POM_PATH -P ci-cd

    - name: Publish to GitHub Packages
      if: ${{ github.base_ref == '' && startsWith( github.ref, 'refs/heads/release-' ) }}
      run: mvn -B deploy --file $POM_PATH -P ci-cd,github-packages
